apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-wrokflows
  namespace: argo
  labels:
    cluster: c0
    app: argo-workflows
spec:
  project: default
  source:
    repoURL: https://github.com/LoogleCZ/kad-example.git
    targetRevision: HEAD
    path: argo/workflows
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
