apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: loki
  labels:
    cluster: c0
    app: loki
spec:
  project: default
  source:
    repoURL: https://github.com/LoogleCZ/kad-example.git
    targetRevision: HEAD
    path: loki/
  destination:
    name: in-cluster
    namespace: loki
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
